### ISSUE TITLE
API - Auth

### ISSUE THREAD

**Issue by AlexStansfield** [apacig/opendesign#4]
Takes `code` in request.

1. Use a GitHub OAuth library (https://github.com/KnpLabs/php-github-api) to get Access Token from code - [api](https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-authorization-options-for-oauth-apps/#2-users-are-redirected-back-to-your-site-by-github)
2. Get Access Token and call user api (`/user`) with [token](https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-authorization-options-for-oauth-apps/#3-use-the-access-token-to-access-the-api)
3. Check User table for user with same github ID.
4. If no user then create user
5. Do OAuth Stuff with passport (see comment)
6. Return an Auth Token

**Comment by samundra** [comment]
@AlexStansfield Maybe https://laravel.com/docs/5.5/passport

**Comment by AlexStansfield** [comment]
Closed by #29
